runtime: nodejs10
handlers:
  # Serve all static files with urls ending with a file extension
- url: /(.*\..+)$ 
  static_files: dist/\1
  upload: dist/(.*\..+)$
  # catch all handler to index.html
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  redirect_http_response_code: 301
- url: /robots.txt
  static_files: /robots.txt
  upload: /robots.txt